version: '2'
services:
    web:
        build: .
        image: django-sandbox:latest
        command: python api/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
